<?php

namespace app\models;
use yii\helpers\Url;
use Yii;

/**
 * This is the model class for table "history_cards".
 *
 * @property int $id
 * @property string $image
 * @property string $title
 * @property int $order_number
 */
class HistoryCards extends \yii\db\ActiveRecord
{
    public $imageFile;

    public function getFileUploadFolderPath()
    {
        $path = Yii::$app->basePath .'/web/uploads/history_card/';
        if(!file_exists($path)){
            mkdir($path, 0700);
        }
        return $path;
    }

    public function imgUrl()
    {
        return Url::base(true) .'/uploads/history_card/' . $this->image;
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'history_cards';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'url', 'order_number'], 'required'],
            [['order_number'], 'integer'],
            [['image', 'title'], 'string', 'max' => 255],
            [['url'], 'string', 'max' => 500],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'image' => Yii::t('app', 'Image'),
            'title' => Yii::t('app', 'Title'),
            'url' => Yii::t('app', 'Url'),
            'order_number' => Yii::t('app', 'Order Number'),
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
            $baseFileName = $this->imageFile->baseName . '.' . $this->imageFile->extension;
            $uploadPath = $this->getFileUploadFolderPath() . $baseFileName;
            $this->imageFile->saveAs($uploadPath);
            $this->image = $baseFileName;
            return $this->update(false);
        } else {
            return false;
        }
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        if(file_exists($this->image)){
            unlink($this->image);
        }
    }
}
