<?php

namespace app\models;

use Yii;
use yii\helpers\Url;
/**
 * This is the model class for table "slider_items".
 *
 * @property int $id
 * @property string $file_path
 * @property string $title
 * @property string $description
 * @property int $order_number
 */
class SliderItems extends \yii\db\ActiveRecord
{
    /**
     * @var UploadedFile
     */
    public $imageFile;

    public function getFileUploadFolderPath()
    {
        $path = Yii::$app->basePath .'/web/uploads/slider/';
        if(!file_exists($path)){
            mkdir($path, 0700);
        }
        return $path;
    }

    public function imgUrl()
    {
        return Url::base(true) .'/uploads/slider/' . $this->file_path;
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'slider_items';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'description', 'order_number'], 'required'],
            [['description'], 'string'],
            [['order_number'], 'integer'],
            [['file_path', 'title'], 'string', 'max' => 255],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'file_path' => Yii::t('app', 'File Path'),
            'title' => 'Заголовок',
            'description' => 'Описание',
            'order_number' => 'Порядковый номер',
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
            $baseFileName = $this->imageFile->baseName . '.' . $this->imageFile->extension;
            $uploadPath = $this->getFileUploadFolderPath() . $baseFileName;
            $this->imageFile->saveAs($uploadPath);
            $this->file_path = $baseFileName;
            return $this->update(false);
        } else {
            return false;
        }
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        if(file_exists($this->file_path)){
            unlink($this->file_path);
        }
    }
}
