<?php

namespace app\models;
use yii\helpers\Url;
use Yii;

/**
 * This is the model class for table "three_card".
 *
 * @property int $id
 * @property string $image
 * @property string $title
 * @property string $description
 * @property int $order_number
 */
class ThreeCard extends \yii\db\ActiveRecord
{
    /**
     * @var UploadedFile
     */
    public $imageFile;

    public function getFileUploadFolderPath()
    {
        $path = Yii::$app->basePath .'/web/uploads/three_card/';
        if(!file_exists($path)){
            mkdir($path, 0700);
        }
        return $path;
    }

    public function imgUrl()
    {
        return Url::base(true) .'/uploads/three_card/' . $this->image;
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'three_card';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'description', 'order_number'], 'required'],
            [['description'], 'string'],
            [['order_number'], 'integer'],
            [['image', 'title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'image' => 'Картинка',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'order_number' => 'Порядковый номер',
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
            $baseFileName = $this->imageFile->baseName . '.' . $this->imageFile->extension;
            $uploadPath = $this->getFileUploadFolderPath() . $baseFileName;
            $this->imageFile->saveAs($uploadPath);
            $this->image = $baseFileName;
            return $this->update(false);
        } else {
            return false;
        }
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        if(file_exists($this->image)){
            unlink($this->image);
        }
    }
}
